pref("extensions.zotero-mineru.mineruApiBaseURL", "https://mineru.net/api/v4");
pref("extensions.zotero-mineru.mineruModelVersion", "pipeline");
pref("extensions.zotero-mineru.mineruTitlePrefix", "MinerU Parse");
pref("extensions.zotero-mineru.mineruPollIntervalSec", 3);
pref("extensions.zotero-mineru.mineruTimeoutSec", 120);
pref("extensions.zotero-mineru.mineruDailyFileLimit", 5000);
pref("extensions.zotero-mineru.mineruPriorityPageLimit", 1000);
pref("extensions.zotero-mineru.mineruTokens", "");
pref("extensions.zotero-mineru.mineruUsageJSON", "{}");
pref("extensions.zotero-mineru.kbRootPath", "");
