pref("extensions.zoteru.mineruApiBaseURL", "https://mineru.net/api/v4");
pref("extensions.zoteru.mineruModelVersion", "pipeline");
pref("extensions.zoteru.mineruTitlePrefix", "MinerU Parse");
pref("extensions.zoteru.mineruPollIntervalSec", 3);
pref("extensions.zoteru.mineruTimeoutSec", 120);
pref("extensions.zoteru.mineruDailyFileLimit", 5000);
pref("extensions.zoteru.mineruPriorityPageLimit", 1000);
pref("extensions.zoteru.mineruTokens", "");
pref("extensions.zoteru.mineruUsageJSON", "{}");
pref("extensions.zoteru.kbRootPath", "");
